### ISSUE TITLE
[BUG] [Extensions] Not able to register Routes with similar semantics from RestActions

### ISSUE THREAD

**Issue by vibrantvarun** [opensearch-project/opensearch-sdk-java#654] opened 2023-04-06 17:16 UTC
### What is the bug?
The get detector has the following route.
```
/detectors/{detectorId}

return ImmutableList
            .of(
                // GET
                new RouteHandler(
                    RestRequest.Method.GET,
                    String.format(Locale.ROOT, "%s/{%s}", AnomalyDetectorExtension.AD_BASE_DETECTORS_URI, DETECTOR_ID),
                    handleRequest
                )
            );

```

The detector stats API requires following route to be registered.
```
/detectors/{nodeId}/stats

new RouteHandler(
                    RestRequest.Method.GET,
                    String.format(Locale.ROOT, "%s/{%s}/%s", AnomalyDetectorExtension.AD_BASE_DETECTORS_URI, NODE_ID, "stats"),
                    handleRequest
                ),

```

However, the routes  for stats API cannot be registered due to the error mentioned below
```java
Exception in thread "main" java.lang.IllegalArgumentException: Trying to use conflicting wildcard names for same path: detectorID and nodeId
        at org.opensearch.common.path.PathTrie$TrieNode.updateKeyWithNamedWildcard(PathTrie.java:131)
        at org.opensearch.common.path.PathTrie$TrieNode.insert(PathTrie.java:159)
        at org.opensearch.common.path.PathTrie$TrieNode.insert(PathTrie.java:176)
        at org.opensearch.common.path.PathTrie$TrieNode.insert(PathTrie.java:176)
        at org.opensearch.common.path.PathTrie.insert(PathTrie.java:329)
        at org.opensearch.sdk.ExtensionRestPathRegistry.registerHandler(ExtensionRestPathRegistry.java:38)
        at org.opensearch.sdk.ExtensionsRunner.<init>(ExtensionsRunner.java:247)
        at org.opensearch.sdk.ExtensionsRunner.run(ExtensionsRunner.java:744)
        at org.opensearch.ad.AnomalyDetectorExtension.main(AnomalyDetectorExtension.java:588)
```
### How can one reproduce the bug?
We can reproduce the bug by trying to register any path which has 

`/detectors/{anyValue}`

### What is the expected behavior?
The extensions framework should allow registering the impacted routes

### Do you have any additional context?
I think the problem is with using Trie data structure in registering paths. Boiling down it is not able to differentiate between the key of two paths.

**Comment by dbwiddis** [comment] 2023-04-06 19:02
Root cause of the bug is the use of `insert()` rather than `insertOrUpdate()` in the `PathTrie`, which required tracking/updating a `MethodHandlers` object.  By using the method (string) as part of the path name, this effectively worked around the need to update the methods... but breaks with different "same method different wildcard" names as shown.

Solution: create an SDK variant of `MethodHandlers`.

**Comment by owaiskazi19** [comment] 2023-04-06 23:02
Facing the same issue for Search Detectors:

```java
Exception in thread "main" java.lang.IllegalArgumentException: Path [POST /detectors/_search] already has a value [org.opensearch.ad.rest.RestSearchAnomalyDetectorAction@5f8f1712]
        at org.opensearch.common.path.PathTrie$TrieNode.insert(PathTrie.java:168)
        at org.opensearch.common.path.PathTrie$TrieNode.insert(PathTrie.java:176)
        at org.opensearch.common.path.PathTrie$TrieNode.insert(PathTrie.java:176)
        at org.opensearch.common.path.PathTrie.insert(PathTrie.java:329)
        at org.opensearch.sdk.ExtensionRestPathRegistry.registerHandler(ExtensionRestPathRegistry.java:38)
        at org.opensearch.sdk.ExtensionsRunner.<init>(ExtensionsRunner.java:247)
        at org.opensearch.sdk.ExtensionsRunner.run(ExtensionsRunner.java:744)
        at org.opensearch.ad.AnomalyDetectorExtension.main(AnomalyDetectorExtension.java:612)

**Comment by dbwiddis** [comment] 2023-04-06 23:05
Working on a fix and replicated the same way `RestController` does this but still running into this issue.

Temporary workaround: change your rest paths to detectors1 and detectors2 etc. while I sort this out.  I don't see how this isn't already failing for plugins with those paths....

**Comment by owaiskazi19** [comment] 2023-04-06 23:07
> I don't see how this isn't already failing for plugins with those paths....

Is it because plugin is using `ReplacedRoutes` for such cases? Do you think as a part of this fix we should add the same for extensions? It will also help for BWC testing.

**Comment by dbwiddis** [comment] 2023-04-06 23:11
Possibly.  I just found `testRegisterSecondMethodWithDifferentNamedWildcard()` in `RestControllerTests` which fails on the exact case here so clearly whatever is being registered is not what I think it is.

**Comment by dbwiddis** [comment] 2023-04-06 23:21
Nope, the plugins are registering handlers via this code in `RestController`:
```java
    public void registerHandler(final RestHandler restHandler) {
        restHandler.routes().forEach(route -> registerHandler(route.getMethod(), route.getPath(), restHandler));
        restHandler.deprecatedRoutes()
            .forEach(route -> registerAsDeprecatedHandler(route.getMethod(), route.getPath(), restHandler, route.getDeprecationMessage()));
        restHandler.replacedRoutes()
            .forEach(
                route -> registerWithDeprecatedHandler(
                    route.getMethod(),
                    route.getPath(),
                    restHandler,
                    route.getDeprecatedMethod(),
                    route.getDeprecatedPath()
                )
            );
    }
```
That first line `restHandler.routes().forEach(route -> registerHandler(route.getMethod(), route.getPath(), restHandler));` is the portion we're implementing.  It calls:
```java
    protected void registerHandler(RestRequest.Method method, String path, RestHandler handler) {
        if (handler instanceof BaseRestHandler) {
            usageService.addRestHandler((BaseRestHandler) handler);
        }
        registerHandlerNoWrap(method, path, handlerWrapper.apply(handler));
    }
```
Which then calls:
```
    private void registerHandlerNoWrap(RestRequest.Method method, String path, RestHandler maybeWrappedHandler) {
        handlers.insertOrUpdate(
            path,
            new MethodHandlers(path, maybeWrappedHandler, method),
            (mHandlers, newMHandler) -> mHandlers.addMethods(maybeWrappedHandler, method)
        );
    }
```
I have exactly replicated this last method and it fails, and looks like it is expected to fail.

**Comment by owaiskazi19** [comment] 2023-04-06 23:39
I see. For Search, there are 3 RestActions extending the same AbstractSearchAction and registering the routes like [this](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/AbstractSearchAction.java#L106) and [this](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/AbstractSearchAction.java#L119).
The urlPath and deprecatedPaths are defined [here](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/RestSearchAnomalyDetectorAction.java#L28) and [here](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/RestSearchAnomalyDetectorAction.java#L29) which are passed in `super`. 
Since AbstractSearchAction has `route` and `ReplacedRoute` this is not an issue with Plugin. In extensions for now we are supporting just `routes` because of which we can't register the API with same path.

**Comment by dbwiddis** [comment] 2023-04-06 23:46
The issue you're facing in Search (already has a value) is different than the wildcard issue (conflicting wildcards).

**Comment by dbwiddis** [comment] 2023-04-07 00:00
OK, so this does have to do with ReplacedRoutes.

The path indicated for Get Detector in the initial post here doesn't match the plugin.
```
/detectors/{detectorId}

return ImmutableList
            .of(
                // GET
                new RouteHandler(
                    RestRequest.Method.GET,
                    String.format(Locale.ROOT, "%s/{%s}", AnomalyDetectorExtension.AD_BASE_DETECTORS_URI, DETECTOR_ID),
                    handleRequest
                )
            );
```
But plugin has:
```java
    @Override
    public List<Route> routes() {
        return ImmutableList
            .of(
                // Opensearch-only API. Considering users may provide entity in the search body, support POST as well.
                new Route(
                    RestRequest.Method.POST,
                    String.format(Locale.ROOT, "%s/{%s}/%s", AnomalyDetectorPlugin.AD_BASE_DETECTORS_URI, DETECTOR_ID, PROFILE)
                ),
                new Route(
                    RestRequest.Method.POST,
                    String.format(Locale.ROOT, "%s/{%s}/%s/{%s}", AnomalyDetectorPlugin.AD_BASE_DETECTORS_URI, DETECTOR_ID, PROFILE, TYPE)
                )
            );
    }
```
The shorter URL is the replaced routes "alias" for it.

**Comment by dbwiddis** [comment] 2023-04-07 00:39
So, wrapping this up:
1. I don't think there's a bug in how we register routes.  I still might just update the code I already wrote to conform exactly to how the `RestController` does it anyway, just to be sure, but it won't fix this issue.
2. We should change the routes we have for AD to match the actual `routes()` return value. That will near-term solve this bug, even if we have to use longer paths during our testing/validation in the near term.
3. We should implement ReplacedRoutes extension point. I think there's an issue for that already. If not, we'll add it.

**Comment by dbwiddis** [comment] 2023-04-09 01:05
So the deprecated routes just register more routes (with a log message) and the replace routes do both (regular AND deprecated).   So they aren't going to fix this.

Root cause is I think the get detector route registered is incorrect and needs to be fixed.

**Comment by dbwiddis** [comment] 2023-04-09 01:36
So deprecated and replaced routes just register additional routes and don't fix this (perceived) problem.   It's good to add them but they aren't a bug fix.  Because there's no bug. :) 

> The detector stats API requires following route to be registered.
> 
> ```
> /detectors/{nodeId}/stats
> 
> new RouteHandler(
>                     RestRequest.Method.GET,
>                     String.format(Locale.ROOT, "%s/{%s}/%s", AnomalyDetectorExtension.AD_BASE_DETECTORS_URI, NODE_ID, "stats"),
>                     handleRequest
>                 ),
> ```

Stats does not use `AD_BASE_DETECTORS_URI`, it uses `AD_BASE_URI`.

The route is not `/detectors/{nodeId}/stats`, it is `/{nodeId}/stats`.

**Comment by dbwiddis** [comment] 2023-04-09 01:41
> Facing the same issue for Search Detectors:
> 
> ```java
> Exception in thread "main" java.lang.IllegalArgumentException: Path [POST /detectors/_search] already has a value [org.opensearch.ad.rest.RestSearchAnomalyDetectorAction@5f8f1712]
> ```

Hardcoded paths (`_search`) take precedence over wildcards, and don't conflict, so this is not a problem with the registry.  It may be that you have the path registered in a superclass and are inheriting it in multiple subclasses?

**Closed** 2023-05-01 01:54 UTC
Labels: wontfix
