### ISSUE TITLE
[FEATURE] Refactor ExtensionsRunner class

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#116] opened 2022-08-31 04:15 UTC
### Is your feature request related to a problem?

> ExtensionsRunner is getting big, could we compartmentalize this functionality?  Maybe there is a pattern like configuration/registration/request handling?

_Originally posted by @peternied in https://github.com/opensearch-project/opensearch-sdk-java/pull/109#discussion_r958898763_

### What solution would you like?

There are 513 lines.
 - Up to line 156 is headers, constructors, initializers, getters, setters, etc.
 - Line 157-244 is handler methods that are registered in lines 328-390
 - Line 246-390 is initializing the transport service and registering the above request handlers
 - Line 392-471 is sending transport requests
 - Line 473-513 is back to setters and startup methods

We can definitely separate out lines 157-471 into at least one other class, possibly two or three.
 - each of the handlers in lines 157-244 could probably have its own class.
 - ~the `transportService.registerRequestHandler()` calls are all the same except for two lines, and could benefit from a helper method for the 80-90% of that code that is common.~ _(these are all single method calls but take up several lines, probably ok to leave)._
 - The Netty4 and initialize transport service can probably be moved to their own class. (Speaking of netty4, there are some old third party license files that can be removed).

### What alternatives have you considered?

Doing nothing. It's tempting.

### Do you have any additional context?

Like most code, this starts small and grows to the point where the problem is obvious. We're there.

**Comment by mloufra** [comment] 2022-09-07 21:58
After I did same research, refactoring class is to delete duplicate code and split the class has many method or feature into several classes have single method or feature. In that way, we can make code clean and clear and easily for everyone to maintain and add new feature. And what I am understanding for this issue is to create a new class and move the code which from line 168 `InitializeExtensionsResponse handleExtensionInitRequest(InitializeExtensionsRequest extensionInitRequest) ` to line 250 `RestExecuteOnExtensionResponse handleRestExecuteOnExtensionRequest(RestExecuteOnExtensionRequest request)` into this new class and another new class for `public Netty4Transport getNetty4Transport(Settings settings, ThreadPool threadPool)` method. (the code keeps adding, so just for making sure)  If my understanding is correct, is there any recommendation name for these two class.

**Comment by saratvemulapalli** [comment] 2022-09-07 23:39
>What alternatives have you considered?
Doing nothing. It's tempting.

😆

**Comment by mloufra** [comment] 2022-09-08 17:28
> We can definitely separate out lines 157-471 into at least one other class, possibly two or three.
> 
> * each of the handlers in lines 157-244 could probably have its own class.
> * ~the `transportService.registerRequestHandler()` calls are all the same except for two lines, and could benefit from a helper method for the 80-90% of that code that is common.~ _(these are all single method calls but take up several lines, probably ok to leave)._
> * The Netty4 and initialize transport service can probably be moved to their own class. (Speaking of netty4, there are some old third party license files that can be removed).

The following is plan to refactor class for ExtensionsRunner

- Having a new class to handle handler method in line 157-244
- Having a new class to handle Netty4 and initialize transport service method in line 252-327
- Having a new class to handle transport request method in line 398-477

**Comment by dbwiddis** [comment] 2022-09-14 18:18
The transport requests all follow the model, so this code could be extracted:
```java
public void sendFooRequest(TransportService transportService) {
    logger.info("Sending " + foo + " request to OpenSearch");
    TransportResponseHandler<Foo> handler = new FooHandler();
    try {
        transportService.sendRequest(
            opensearchNode,
            ExtensionsOrchestrator.REQUEST_FOO,
            new ExtensionRequest(ExtensionsOrchestrator.RequestType.REQUEST_FOO),
            fooResponseHandler
        );
    } catch (Exception e) {
        logger.info("Failed to send " + foo + " request to OpenSearch", e);
    }
}
```
We could create a new class and instantiate it with `transportService` and `opensearchNode` in its constructor.

Then we could create a `sendExtensionRequest` method which takes as parameters:
 - String for the request type
 - the enum for the Request 
 - the Response handler
 - possibly might need the class type for the `<T>` needed in the `TransportResponseHandler`.

**Comment by mloufra** [comment] 2022-09-14 19:46
> The transport requests all follow the model, so this code could be extracted:
> 
> ```java
> public void sendFooRequest(TransportService transportService) {
>     logger.info("Sending " + foo + " request to OpenSearch");
>     TransportResponseHandler<Foo> handler = new FooHandler();
>     try {
>         transportService.sendRequest(
>             opensearchNode,
>             ExtensionsOrchestrator.REQUEST_FOO,
>             new ExtensionRequest(ExtensionsOrchestrator.RequestType.REQUEST_FOO),
>             fooResponseHandler
>         );
>     } catch (Exception e) {
>         logger.info("Failed to send " + foo + " request to OpenSearch", e);
>     }
> }
> ```
> 
> We could create a new class and instantiate it with `transportService` and `opensearchNode` in its constructor.
> 
> Then we could create a `sendExtensionRequest` method which takes as parameters:
> 
> * String for the request type
> * the enum for the Request
> * the Response handler
> * possibly might need the class type for the `<T>` needed in the `TransportResponseHandler`.

@dbwiddis 
Let me clarification to make sure whether my understanding for this comment is correct or not. What will be done is that moving the `transportService` method `startTransportService` `sendRegisterRestActionsRequest` `sendClusterStateRequest` `sendClusterSettingsRequest` `sendLocalNodeRequest` and `opensearchNode` method `setOpensearchNode` `getOpensearchNode` to new folder called `transport`. 

Then create a new method based on the example code which shows on comment to make connect between `transportService` class and `ExtensionsRunner` class.

For the `transportService` method, do I need to separate these method in different class?

**Comment by dbwiddis** [comment] 2022-09-14 21:10
> What will be done is that moving the `transportService` method (`startTransportService` `sendRegisterRestActionsRequest` `sendClusterStateRequest` `sendClusterSettingsRequest` `sendLocalNodeRequest`) and `opensearchNode` method (`setOpensearchNode` `getOpensearchNode`) to new folder called `transport`.
> 
> Then create a new method based on the example code which shows on comment to make connect between `transportService` class and `ExtensionsRunner` class.

@mloufra not quite.  Let me go back to the "why" of this refactoring.   When you see [the same code repeated a lot](https://dzone.com/articles/software-design-principles-dry-and-kiss) it's good to put the repetitive stuff in one location so there's only a single method to test/debug.  Lots of bugs slip in during copy/paste code where someone forgot to change one of the things they copied (for example, the log message on failure for the `sendLocalNodeRequest` method was copied from the `sendClusterSettingsRequest` method, and not changed!  Minor bug with logging but causes bigger issues when it's logic-impacting code.)

In this case, the "interesting" and "different" part of the code is in the embedded `transportService.sendRequest()` method calls.  The rest of these methods is just repetition of logging and exception handling.

So the goal here is to create a single "helper" method somewhere (either in ExtensionsRunner, in an existing class related to the TransportService, or in a new class you create) that does the logging and exception handling parts.  Then you can have just a single method call for each type in ExtensionsRunner passing the objects that are different to that same helper method.

**Comment by mloufra** [comment] 2022-09-14 22:08
Thanks @dbwiddis for your clarification. I will update that on my plan.

**Comment by mloufra** [comment] 2022-09-26 23:26
Due to delays caused by too frequent merge conflicts, I raise a [PR](https://github.com/opensearch-project/opensearch-sdk-java/pull/158) for first step of my plan. After this PR getting merged, I will continue on next step.

**Closed** 2022-10-13 18:59 UTC
Labels: enhancement, good first issue
